credentials:
  usernames:
    Joel:
      email: joel@northpharm.local
      name: Joel
      password: "$2b$12$goBqSoWQqDQ524cD8Pi0KuknFQ0WPl3vfxZBbPGsoimNK4xdunqBy"
      role: admin

    Desmond:
      email: desmond@northpharm.local
      name: Desmond
      password: "$2b$12$ACh7A1IfPeEFP5IfHpv.oO.wVhWfPHTOJGuszYEba6WSd0IXGFn1O"
      role: admin

    NPDT:
      email: npdt@northpharm.local
      name: driver
      password: "$2b$12$5m6gy9UppBUDR7D7qGyAOOms5YgxHyZnf/mO3Vg8Dig9o/pT05rte"
      role: user

    StuartPark:
      email: Spp@northpharm.local
      name: Spp
      password: "123456"
      role: user

cookie:
  expiry_days: 30
  key: e153daa64f4f9c0834ac6ac20db2b55c564be7b1c4fc3d5627553b937e221110
  name: np_operations_cookie

preauthorized:
  emails: []