credentials:
  usernames:
    Joel:
      email: joel@northpharm.local
      name: Joel
      password: "191312"
      role: admin

    Desmond:
      email: desmond@northpharm.local
      name: Desmond
      password: "128888"
      role: admin

    driver:
      email: npdt@northpharm.local
      name: driver
      password: "123456"
      role: user

    Spp:
      email: Spp@northpharm.local
      name: Spp
      password: "123456"
      role: user

cookie:
  expiry_days: 90
  key: e153daa64f4f9c0834ac6ac20db2b55c564be7b1c4fc3d5627553b937e221110
  name: np_operations_cookie

preauthorized:
  emails: []
